/**
 * Catalogue des mesures du simulateur.
 *
 * Règles éditoriales (constitution de neutralité) :
 *  - chaque montant est un ORDRE DE GRANDEUR, sa base est dans `basis` ;
 *  - aucune mesure n'est présentée comme bonne ou mauvaise : on décrit ce
 *    qu'elle fait, qui elle concerne (`incidence`) et ce que le moteur en
 *    déduit mécaniquement ;
 *  - le catalogue couvre volontairement tout l'échiquier : à chaque mesure
 *    correspond, autant que possible, sa symétrique.
 */

import type { MeasureDef } from './measures';

export const MEASURES: MeasureDef[] = [
  /* ═════════════ RECETTES EN HAUSSE ═════════════ */

  {
    id: 'tva_normal',
    title: 'Relever le taux normal de TVA',
    desc: 'Le taux de 20 % (biens et services courants) augmente. Rendement fort, payé par tous les consommateurs.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 8,
    param: { unit: 'pt', min: 0.5, max: 3, step: 0.5, default: 1, perUnit: 8 },
    lever: 'tax_conso',
    social: -2,
    phase: 'immediate',
    incidence: 'Tous les ménages, davantage les plus modestes (part de la consommation dans le revenu).',
    basis: '≈ 8 Md€ par point de taux normal (rendement TVA 2024 : 208 Md€).',
  },
  {
    id: 'tva_reduit',
    title: 'Relever le taux réduit de TVA (10 %)',
    desc: 'Restauration, travaux, transports : le taux intermédiaire augmente.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 3,
    param: { unit: 'pt', min: 1, max: 5, step: 1, default: 1, perUnit: 3 },
    lever: 'tax_conso',
    social: -2,
    phase: 'immediate',
    incidence: 'Consommateurs des secteurs concernés ; secteurs à forte intensité de main-d’œuvre.',
    basis: '≈ 3 Md€ par point sur l’assiette du taux à 10 %.',
  },
  {
    id: 'csg_hausse',
    title: 'Augmenter la CSG',
    desc: 'La contribution sociale généralisée, assise sur presque tous les revenus, augmente.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 7,
    param: { unit: 'pt', min: 0.5, max: 2, step: 0.5, default: 0.5, perUnit: 14 },
    lever: 'tax_menages',
    social: -2,
    phase: 'immediate',
    incidence: 'Tous les revenus (salaires, retraites, capital), à assiette très large.',
    basis: '≈ 14 Md€ par point de CSG (toutes assiettes).',
  },
  {
    id: 'isf',
    title: 'Rétablir un impôt sur la fortune',
    desc: 'Un impôt annuel sur les patrimoines nets supérieurs à 1,3 M€, sur le modèle d’avant 2018.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 4.5,
    lever: 'tax_menages_aises',
    social: 1,
    phase: 'progressive',
    incidence: 'Environ 350 000 foyers les plus patrimoniaux.',
    basis: 'Rendement du dernier ISF (2017) : ≈ 4,2 Md€, actualisé.',
  },
  {
    id: 'isf_climat',
    title: 'Créer un ISF climatique',
    desc: 'Un impôt sur la fortune modulé selon l’empreinte carbone des actifs détenus.',
    category: 'ecologie',
    kind: 'recette_plus',
    amount: 3,
    lever: 'tax_menages_aises',
    social: 1,
    phase: 'slow',
    incidence: 'Grands patrimoines financiers ; suppose un référentiel carbone des actifs.',
    basis: 'Chiffrages associatifs et parlementaires : 2 à 5 Md€ selon barème.',
  },
  {
    id: 'ir_tranche',
    title: 'Créer une tranche d’IR à 50 %',
    desc: 'Une tranche supplémentaire d’impôt sur le revenu au-delà de 250 000 € par part.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 2,
    lever: 'tax_menages_aises',
    social: 1,
    phase: 'immediate',
    incidence: 'Les 0,2 % de foyers aux revenus les plus élevés.',
    basis: 'Chiffrages parlementaires de mesures similaires : 1,5 à 2,5 Md€.',
  },
  {
    id: 'ir_gel_bareme',
    title: 'Geler le barème de l’impôt sur le revenu',
    desc: 'Le barème n’est pas indexé sur l’inflation : mécaniquement, l’impôt augmente.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 2,
    lever: 'tax_menages',
    social: -2,
    phase: 'immediate',
    incidence: 'Tous les foyers imposables, y compris ceux qui entrent dans l’impôt.',
    basis: '≈ 2 Md€ par année de non-indexation (PLF successifs).',
  },
  {
    id: 'pfu_hausse',
    title: 'Relever la flat tax sur les revenus du capital',
    desc: 'Le prélèvement forfaitaire unique de 30 % sur dividendes et plus-values augmente.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 2,
    param: { unit: 'pt', min: 2, max: 10, step: 2, default: 5, perUnit: 0.5 },
    lever: 'tax_menages_aises',
    social: 0,
    phase: 'immediate',
    incidence: 'Détenteurs de capital financier ; sensible aux comportements d’arbitrage.',
    basis: '≈ 0,5 Md€ par point, avant réaction des contribuables (Conseil des prélèvements obligatoires).',
  },
  {
    id: 'successions',
    title: 'Durcir les droits de succession élevés',
    desc: 'Abattements réduits et taux relevés sur les transmissions supérieures à 1 M€ par héritier.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 3,
    lever: 'tax_menages_aises',
    social: -1,
    phase: 'progressive',
    incidence: 'Les 10 % de successions les plus importantes.',
    basis: 'Conseil d’analyse économique (2021) : 2 à 4 Md€ selon barème.',
  },
  {
    id: 'exit_tax',
    title: 'Renforcer l’exit tax',
    desc: 'Taxation des plus-values latentes lors d’un départ fiscal à l’étranger.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 0.8,
    lever: 'tax_menages_aises',
    social: 1,
    phase: 'progressive',
    incidence: 'Contribuables très fortunés quittant la France.',
    basis: 'Rendement du dispositif d’avant 2019, réévalué : 0,5 à 1 Md€.',
  },
  {
    id: 'foncier_valeurs',
    title: 'Réviser les valeurs locatives cadastrales',
    desc: 'Les bases de la taxe foncière, figées depuis 1970, sont actualisées.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 3,
    lever: 'tax_menages',
    social: -2,
    phase: 'slow',
    incidence: 'Propriétaires ; forts effets redistributifs entre territoires.',
    basis: 'Travaux DGFiP sur la révision des valeurs locatives des locaux d’habitation.',
  },
  {
    id: 'logements_vacants',
    title: 'Taxer plus fortement les logements vacants',
    desc: 'La taxe sur les logements inoccupés est relevée et étendue.',
    category: 'logement',
    kind: 'recette_plus',
    amount: 0.5,
    lever: 'tax_menages_aises',
    social: 2,
    phase: 'progressive',
    incidence: 'Propriétaires de logements vacants en zone tendue.',
    basis: 'Rendement actuel ≈ 0,2 Md€ ; doublement à triplement envisagé.',
  },
  {
    id: 'is_hausse',
    title: 'Augmenter l’impôt sur les sociétés',
    desc: 'Le taux normal d’IS remonte au-dessus de 25 %.',
    category: 'fiscalite_entreprises',
    kind: 'recette_plus',
    amount: 3,
    param: { unit: 'pt', min: 1, max: 8, step: 1, default: 3, perUnit: 3 },
    lever: 'tax_entreprises',
    social: 0,
    phase: 'immediate',
    incidence: 'Les entreprises bénéficiaires, surtout les grandes.',
    basis: '≈ 3 Md€ par point (rendement IS 2024 : 84 Md€ au taux de 25 %).',
  },
  {
    id: 'is_surtaxe',
    title: 'Surtaxer les très grandes entreprises',
    desc: 'Contribution exceptionnelle sur les sociétés réalisant plus d’un milliard de chiffre d’affaires.',
    category: 'fiscalite_entreprises',
    kind: 'recette_plus',
    amount: 8,
    lever: 'tax_entreprises',
    social: 1,
    phase: 'immediate',
    incidence: 'Environ 400 groupes ; dispositif voisin de celui voté pour 2025.',
    basis: 'Chiffrage du PLF 2025 pour la contribution exceptionnelle : 8 Md€.',
  },
  {
    id: 'superprofits',
    title: 'Taxer les rentes énergétiques exceptionnelles',
    desc: 'Contribution sur les profits exceptionnels des producteurs d’énergie.',
    category: 'fiscalite_entreprises',
    kind: 'recette_plus',
    amount: 5,
    lever: 'tax_entreprises',
    social: 2,
    phase: 'immediate',
    incidence: 'Énergéticiens ; rendement très dépendant des prix de marché.',
    basis: 'Rendement des contributions 2022-2023 (CRIM et mécanismes UE).',
  },
  {
    id: 'ttf',
    title: 'Élargir la taxe sur les transactions financières',
    desc: 'Taux relevé et assiette étendue aux transactions intrajournalières.',
    category: 'fiscalite_entreprises',
    kind: 'recette_plus',
    amount: 2,
    lever: 'tax_menages_aises',
    social: 1,
    phase: 'progressive',
    incidence: 'Acteurs de marché ; incidence finale partagée avec les épargnants.',
    basis: 'TTF actuelle ≈ 2 Md€ ; doublement estimé par des rapports parlementaires.',
  },
  {
    id: 'taxe_rachats',
    title: 'Taxer les rachats d’actions',
    desc: 'Une taxe sur les programmes de rachat d’actions des grandes sociétés cotées.',
    category: 'fiscalite_entreprises',
    kind: 'recette_plus',
    amount: 1,
    lever: 'tax_entreprises',
    social: 1,
    phase: 'immediate',
    incidence: 'Grandes entreprises cotées et leurs actionnaires.',
    basis: 'Dispositif du PLF 2025 : ≈ 0,5 à 1 Md€.',
  },
  {
    id: 'gafa',
    title: 'Renforcer la taxe sur les services numériques',
    desc: 'Le taux de la « taxe GAFA » sur le chiffre d’affaires numérique augmente.',
    category: 'numerique',
    kind: 'recette_plus',
    amount: 1.5,
    lever: 'tax_entreprises',
    social: 2,
    phase: 'progressive',
    incidence: 'Plateformes numériques ; répercussion possible sur les annonceurs et vendeurs.',
    basis: 'Rendement actuel ≈ 0,7 Md€ ; doublement du taux.',
  },
  {
    id: 'cir_rabot',
    title: 'Raboter le crédit d’impôt recherche',
    desc: 'Le CIR est recentré sur les PME et plafonné pour les grands groupes.',
    category: 'fiscalite_entreprises',
    kind: 'recette_plus',
    amount: 2,
    lever: 'tax_entreprises',
    social: 0,
    phase: 'progressive',
    incidence: 'Grandes entreprises utilisatrices du CIR (coût actuel ≈ 7 Md€/an).',
    basis: 'Rapports Cour des comptes / CNEPI : 1,5 à 2,5 Md€ récupérables.',
  },
  {
    id: 'niches_menages',
    title: 'Raboter les niches fiscales des ménages',
    desc: 'Plafonnement global durci des réductions et crédits d’impôt.',
    category: 'fiscalite_menages',
    kind: 'recette_plus',
    amount: 5,
    lever: 'tax_menages',
    social: -1,
    phase: 'progressive',
    incidence: 'Foyers utilisant emploi à domicile, investissements locatifs, dons…',
    basis: 'Coût total des dépenses fiscales ménages ≈ 45 Md€ ; rabot de l’ordre de 10 %.',
  },
  {
    id: 'taxe_carbone',
    title: 'Reprendre la trajectoire carbone',
    desc: 'La taxe carbone, gelée depuis 2018, reprend sa hausse (+15 €/tonne).',
    category: 'ecologie',
    kind: 'recette_plus',
    amount: 4,
    lever: 'tax_conso',
    social: -3,
    phase: 'progressive',
    incidence: 'Ménages et entreprises consommateurs d’énergies fossiles, davantage en zone rurale.',
    basis: '≈ 4 Md€ pour +15 €/t (assiette TICPE et carbone).',
  },
  {
    id: 'billets_avion',
    title: 'Taxer davantage les billets d’avion',
    desc: 'La taxe de solidarité sur les billets augmente, surtout en classe affaires.',
    category: 'transports',
    kind: 'recette_plus',
    amount: 1,
    lever: 'tax_conso',
    social: 1,
    phase: 'immediate',
    incidence: 'Voyageurs aériens ; secteur du transport aérien.',
    basis: 'Hausse votée en 2025 : ≈ 1 Md€.',
  },
  {
    id: 'poids_lourds',
    title: 'Créer une écotaxe poids lourds',
    desc: 'Une redevance kilométrique pour les camions sur le réseau national.',
    category: 'transports',
    kind: 'recette_plus',
    amount: 1.2,
    lever: 'tax_conso',
    social: -1,
    phase: 'slow',
    incidence: 'Transport routier de marchandises ; répercussion sur les prix.',
    basis: 'Projet d’écotaxe abandonné en 2014 : rendement net estimé ≈ 1 Md€.',
  },
  {
    id: 'malus_auto',
    title: 'Durcir le malus automobile',
    desc: 'Le malus au poids et au CO₂ des véhicules neufs est renforcé.',
    category: 'ecologie',
    kind: 'recette_plus',
    amount: 1,
    lever: 'tax_conso',
    social: -1,
    phase: 'immediate',
    incidence: 'Acheteurs de véhicules neufs lourds ou émetteurs.',
    basis: 'Rendement du malus actuel ≈ 0,7 Md€ ; durcissement du barème.',
  },
  {
    id: 'accises_sante',
    title: 'Augmenter les accises tabac et alcool',
    desc: 'Fiscalité comportementale renforcée sur le tabac et les alcools.',
    category: 'sante',
    kind: 'recette_plus',
    amount: 3,
    lever: 'tax_conso',
    social: -1,
    phase: 'immediate',
    incidence: 'Consommateurs ; effets attendus sur la consommation et les achats transfrontaliers.',
    basis: 'Rendement tabac ≈ 15 Md€ ; alcools ≈ 4 Md€ : hausse de l’ordre de 15 %.',
  },
  {
    id: 'cotisations_hausse',
    title: 'Augmenter les cotisations vieillesse',
    desc: 'Le taux de cotisation retraite (employeurs et salariés) augmente.',
    category: 'retraites',
    kind: 'recette_plus',
    amount: 8,
    param: { unit: 'pt', min: 0.5, max: 2, step: 0.5, default: 1, perUnit: 8 },
    lever: 'cotisations',
    social: -2,
    phase: 'immediate',
    incidence: 'Salariés et employeurs ; effet direct sur le coût du travail et le salaire net.',
    basis: '≈ 8 Md€ par point de cotisation (assiette salariale ≈ 800 Md€).',
  },
  {
    id: 'fraude',
    title: 'Renforcer la lutte contre la fraude fiscale',
    desc: 'Effectifs de contrôle doublés, données croisées, obligations déclaratives durcies.',
    category: 'fonctionnement_etat',
    kind: 'recette_plus',
    amount: 3,
    lever: 'tax_menages_aises',
    directJobs: 4000,
    social: 3,
    phase: 'slow',
    incidence: 'Fraudeurs ; coût de mise en œuvre déjà déduit.',
    basis: 'Rendement supplémentaire estimé par la Cour des comptes : 2 à 4 Md€/an.',
  },
  {
    id: 'fraude_sociale',
    title: 'Renforcer la lutte contre la fraude sociale',
    desc: 'Contrôles accrus sur les prestations et le travail dissimulé.',
    category: 'social',
    kind: 'recette_plus',
    amount: 2,
    lever: 'tax_entreprises',
    directJobs: 3000,
    social: 2,
    phase: 'slow',
    incidence: 'Fraude aux cotisations (principal gisement) et aux prestations.',
    basis: 'Estimations Urssaf/HCFiPS : fraude aux cotisations 6-8 Md€, recouvrement partiel.',
  },

  /* ═════════════ RECETTES EN BAISSE ═════════════ */

  {
    id: 'tva_necessite',
    title: 'TVA à 0 % sur les produits de première nécessité',
    desc: 'Alimentaire de base, hygiène : le taux de 5,5 % tombe à zéro.',
    category: 'fiscalite_menages',
    kind: 'recette_moins',
    amount: 4,
    lever: 'tax_conso',
    social: 2,
    phase: 'immediate',
    incidence: 'Tous les ménages, gain relatif plus fort pour les plus modestes.',
    basis: 'Assiette du taux réduit alimentaire : ≈ 4 Md€.',
  },
  {
    id: 'tva_energie',
    title: 'TVA à 5,5 % sur l’électricité et le gaz',
    desc: 'L’énergie du logement passe au taux réduit, considérée comme un bien de première nécessité.',
    category: 'fiscalite_menages',
    kind: 'recette_moins',
    amount: 6,
    lever: 'tax_conso',
    social: 2,
    phase: 'immediate',
    incidence: 'Tous les ménages ; gain proportionnel à la consommation d’énergie.',
    basis: 'Assiette TVA énergie domestique : ≈ 6 Md€ de manque à gagner.',
  },
  {
    id: 'ir_baisse',
    title: 'Baisser l’impôt sur le revenu des classes moyennes',
    desc: 'Le taux de la tranche à 30 % diminue.',
    category: 'fiscalite_menages',
    kind: 'recette_moins',
    amount: 5,
    param: { unit: 'pt', min: 1, max: 4, step: 1, default: 2, perUnit: 2.5 },
    lever: 'tax_menages',
    social: 2,
    phase: 'immediate',
    incidence: '≈ 7 millions de foyers imposés dans la tranche à 30 %.',
    basis: '≈ 2,5 Md€ par point de la 2e tranche.',
  },
  {
    id: 'ir_premiere_tranche',
    title: 'Supprimer la première tranche d’impôt sur le revenu',
    desc: 'La tranche à 11 % est supprimée : plusieurs millions de foyers sortent de l’impôt.',
    category: 'fiscalite_menages',
    kind: 'recette_moins',
    amount: 4,
    lever: 'tax_menages',
    social: 2,
    phase: 'immediate',
    incidence: 'Foyers modestes et moyens ; concentre le rendement de l’IR sur moins de contribuables.',
    basis: 'Rendement de la tranche à 11 % : ≈ 4 Md€.',
  },
  {
    id: 'impots_prod',
    title: 'Baisser les impôts de production',
    desc: 'CFE et taxes assises sur l’activité des entreprises réduites.',
    category: 'fiscalite_entreprises',
    kind: 'recette_moins',
    amount: 5,
    lever: 'tax_entreprises',
    social: 0,
    phase: 'progressive',
    incidence: 'Entreprises industrielles surtout ; compensation à prévoir pour les collectivités.',
    basis: 'Sur le modèle des baisses 2021-2023 (CVAE) : 4 à 6 Md€.',
  },
  {
    id: 'cvae_fin',
    title: 'Supprimer le reste de la CVAE',
    desc: 'La cotisation sur la valeur ajoutée des entreprises est définitivement supprimée.',
    category: 'fiscalite_entreprises',
    kind: 'recette_moins',
    amount: 4,
    lever: 'tax_entreprises',
    social: 0,
    phase: 'progressive',
    incidence: 'Entreprises redevables ; recette actuellement affectée aux collectivités.',
    basis: 'Reliquat de CVAE en 2025 : ≈ 4 Md€.',
  },
  {
    id: 'baisse_cotis',
    title: 'Renforcer les allègements de cotisations',
    desc: 'Les exonérations sur les salaires jusqu’à 2,5 SMIC sont étendues.',
    category: 'emploi',
    kind: 'recette_moins',
    amount: 6,
    lever: 'cotisations',
    social: 1,
    phase: 'immediate',
    incidence: 'Employeurs de salariés peu et moyennement qualifiés ; compensé à la Sécurité sociale.',
    basis: 'Coût des allègements existants ≈ 75 Md€ ; extension de l’ordre de 8 %.',
  },
  {
    id: 'heures_sup',
    title: 'Défiscaliser davantage les heures supplémentaires',
    desc: 'Plafond d’exonération relevé, cotisations réduites.',
    category: 'emploi',
    kind: 'recette_moins',
    amount: 2,
    lever: 'cotisations',
    social: 1,
    phase: 'immediate',
    incidence: 'Salariés effectuant des heures supplémentaires ; coût pour la Sécurité sociale.',
    basis: 'Extension du dispositif actuel (≈ 2 Md€).',
  },
  {
    id: 'tva_travaux',
    title: 'TVA à 5,5 % sur tous les travaux de rénovation',
    desc: 'Le taux réduit est généralisé aux travaux d’amélioration du logement.',
    category: 'logement',
    kind: 'recette_moins',
    amount: 1.5,
    lever: 'tax_conso',
    social: 2,
    phase: 'immediate',
    incidence: 'Propriétaires réalisant des travaux ; artisans du bâtiment.',
    basis: 'Écart de taux sur l’assiette travaux : ≈ 1,5 Md€.',
  },
  {
    id: 'credit_garde',
    title: 'Doubler le crédit d’impôt garde d’enfants',
    desc: 'Le soutien fiscal aux frais de garde des jeunes enfants est renforcé.',
    category: 'famille',
    kind: 'recette_moins',
    amount: 1.5,
    lever: 'social_cible',
    social: 2,
    phase: 'immediate',
    incidence: 'Familles avec enfants de moins de 6 ans.',
    basis: 'Coût actuel du crédit d’impôt ≈ 1,4 Md€.',
  },
  {
    id: 'dutreil',
    title: 'Élargir le pacte Dutreil (transmission d’entreprises)',
    desc: 'Les exonérations sur la transmission familiale d’entreprises sont étendues.',
    category: 'fiscalite_entreprises',
    kind: 'recette_moins',
    amount: 1,
    lever: 'tax_menages_aises',
    social: -1,
    phase: 'progressive',
    incidence: 'Familles détentrices d’entreprises transmises.',
    basis: 'Coût actuel du dispositif estimé entre 2 et 3 Md€ ; extension partielle.',
  },
  {
    id: 'tva_restauration',
    title: 'Baisser la TVA de la restauration à 5,5 %',
    desc: 'Le taux de 10 % applicable à la restauration passe au taux réduit.',
    category: 'economie',
    kind: 'recette_moins',
    amount: 2.5,
    lever: 'tax_conso',
    social: 0,
    phase: 'immediate',
    incidence: 'Secteur de la restauration ; répercussion sur les prix incertaine.',
    basis: 'Écart de taux sur l’assiette restauration : ≈ 2,5 Md€.',
  },

  /* ═════════════ DÉPENSES EN HAUSSE ═════════════ */

  /* — Santé — */
  {
    id: 'hopital',
    title: 'Plan hôpital : 15 000 soignants',
    desc: 'Recrutements et revalorisations dans les hôpitaux publics.',
    category: 'sante',
    kind: 'depense_plus',
    amount: 2.5,
    lever: 'fonctionnement',
    directJobs: 15000,
    social: 3,
    phase: 'progressive',
    incidence: 'Patients et personnels hospitaliers ; financé par l’assurance maladie.',
    basis: '≈ 60 k€ de coût complet par poste + enveloppe de revalorisation.',
  },
  {
    id: 'dependance',
    title: 'Grand âge : renforcer la branche autonomie',
    desc: 'Personnels en EHPAD et aide à domicile revalorisée.',
    category: 'sante',
    kind: 'depense_plus',
    amount: 5,
    lever: 'fonctionnement',
    directJobs: 50000,
    social: 3,
    phase: 'progressive',
    incidence: 'Personnes âgées dépendantes et leurs familles.',
    basis: 'Rapports Libault / El Khomri : besoin ≈ 5 Md€/an d’ici 2030.',
  },
  {
    id: 'deserts_medicaux',
    title: 'Lutter contre les déserts médicaux',
    desc: 'Aides à l’installation, centres de santé publics, assistants médicaux.',
    category: 'sante',
    kind: 'depense_plus',
    amount: 1.5,
    lever: 'fonctionnement',
    directJobs: 8000,
    social: 3,
    phase: 'progressive',
    incidence: 'Territoires sous-dotés ; ≈ 6 millions de personnes sans médecin traitant.',
    basis: 'Extension des dispositifs existants (CPTS, assistants médicaux).',
  },
  {
    id: 'sante_mentale',
    title: 'Plan santé mentale et psychiatrie',
    desc: 'Postes en psychiatrie publique, remboursement élargi des psychologues.',
    category: 'sante',
    kind: 'depense_plus',
    amount: 2,
    lever: 'fonctionnement',
    directJobs: 12000,
    social: 3,
    phase: 'progressive',
    incidence: 'Patients en psychiatrie ; secteur en tension documentée.',
    basis: 'Budget actuel de la psychiatrie publique ≈ 10 Md€ ; hausse de 20 %.',
  },
  {
    id: 'prevention',
    title: 'Investir dans la prévention en santé',
    desc: 'Dépistages, vaccination, santé au travail, nutrition.',
    category: 'sante',
    kind: 'depense_plus',
    amount: 2,
    lever: 'fonctionnement',
    directJobs: 6000,
    social: 3,
    phase: 'slow',
    incidence: 'Population générale ; la France consacre ≈ 2 % de sa dépense de santé à la prévention.',
    basis: 'Doublement de l’effort de prévention (≈ 2 Md€).',
  },

  /* — Éducation, recherche — */
  {
    id: 'enseignants',
    title: 'Recruter 20 000 enseignants',
    desc: 'Postes supplémentaires, ciblés sur le primaire et l’éducation prioritaire.',
    category: 'education',
    kind: 'depense_plus',
    amount: 1.3,
    lever: 'fonctionnement',
    directJobs: 20000,
    social: 2,
    phase: 'progressive',
    incidence: 'Élèves et enseignants ; effets de long terme non modélisés ici.',
    basis: '≈ 65 k€ de coût complet moyen par poste.',
  },
  {
    id: 'revalo_profs',
    title: 'Revaloriser le salaire des enseignants de 10 %',
    desc: 'Hausse générale des rémunérations dans l’éducation nationale.',
    category: 'education',
    kind: 'depense_plus',
    amount: 5,
    lever: 'fonctionnement',
    social: 2,
    phase: 'immediate',
    incidence: '≈ 850 000 enseignants ; salaires inférieurs à la moyenne OCDE en milieu de carrière.',
    basis: 'Masse salariale enseignante ≈ 50 Md€.',
  },
  {
    id: 'classes_dedoublees',
    title: 'Réduire les effectifs par classe',
    desc: 'Généralisation du dédoublement au-delà de l’éducation prioritaire.',
    category: 'education',
    kind: 'depense_plus',
    amount: 3,
    lever: 'fonctionnement',
    directJobs: 40000,
    social: 3,
    phase: 'slow',
    incidence: 'Élèves du primaire ; la France a des classes plus chargées que la moyenne OCDE.',
    basis: '≈ 40 000 postes supplémentaires à 65 k€ + locaux.',
  },
  {
    id: 'cantines',
    title: 'Cantine scolaire à 1 € pour tous',
    desc: 'Tarification sociale généralisée dans les cantines des écoles publiques.',
    category: 'education',
    kind: 'depense_plus',
    amount: 2,
    lever: 'social_cible',
    social: 3,
    phase: 'progressive',
    incidence: 'Familles d’élèves ; compensation aux communes gestionnaires.',
    basis: 'Coût du dispositif « cantine à 1 € » étendu à l’ensemble des communes.',
  },
  {
    id: 'universites',
    title: 'Investir dans l’université et la recherche',
    desc: 'Postes, laboratoires, vie étudiante : +5 Md€ par an.',
    category: 'recherche',
    kind: 'depense_plus',
    amount: 5,
    lever: 'invest_public',
    directJobs: 15000,
    social: 2,
    phase: 'progressive',
    incidence: 'Étudiants et chercheurs ; la France investit moins que la moyenne OCDE par étudiant.',
    basis: 'Ordre de grandeur des lois de programmation recherche renforcées.',
  },
  {
    id: 'recherche_3pct',
    title: 'Porter la recherche publique vers 1 % du PIB',
    desc: 'Effort de recherche publique aligné sur l’objectif européen.',
    category: 'recherche',
    kind: 'depense_plus',
    amount: 8,
    lever: 'invest_public',
    directJobs: 25000,
    social: 2,
    phase: 'slow',
    incidence: 'Organismes de recherche, universités ; effets de long terme non modélisés.',
    basis: 'Recherche publique ≈ 0,75 % du PIB ; écart à 1 % ≈ 7-8 Md€.',
  },
  {
    id: 'formation_pro',
    title: 'Plan de formation des demandeurs d’emploi',
    desc: 'Places de formation qualifiante et accompagnement renforcé.',
    category: 'emploi',
    kind: 'depense_plus',
    amount: 3,
    lever: 'fonctionnement',
    directJobs: 10000,
    social: 2,
    phase: 'progressive',
    incidence: 'Demandeurs d’emploi peu qualifiés ; secteurs en tension.',
    basis: 'Ordre de grandeur du Plan d’investissement dans les compétences (≈ 15 Md€ sur 5 ans).',
  },
  {
    id: 'apprentissage_plus',
    title: 'Amplifier le soutien à l’apprentissage',
    desc: 'Primes aux employeurs et places supplémentaires en CFA.',
    category: 'emploi',
    kind: 'depense_plus',
    amount: 2,
    lever: 'social_cible',
    social: 2,
    phase: 'immediate',
    incidence: 'Jeunes en apprentissage et employeurs ; coût actuel du dispositif ≈ 10 Md€.',
    basis: 'Extension de l’aide unique aux employeurs d’apprentis.',
  },

  /* — Écologie, transports, énergie — */
  {
    id: 'invest_eco',
    title: 'Grand plan d’investissement climat',
    desc: 'Rénovation thermique, transports collectifs, énergies décarbonées : investissement public supplémentaire chaque année.',
    category: 'ecologie',
    kind: 'depense_plus',
    amount: 20,
    param: { unit: 'Md€', min: 5, max: 40, step: 5, default: 20, perUnit: 1 },
    lever: 'invest_public',
    social: 1,
    phase: 'progressive',
    incidence: 'BTP, industrie, ménages aidés ; c’est le levier au multiplicateur le plus fort.',
    basis: 'Rapport Pisani-Ferry–Mahfouz (2023) : besoin public ≈ 25-35 Md€/an d’ici 2030.',
  },
  {
    id: 'renovation',
    title: 'Rénovation thermique : 700 000 logements par an',
    desc: 'Aides massives aux rénovations performantes, publiques et privées.',
    category: 'logement',
    kind: 'depense_plus',
    amount: 8,
    lever: 'invest_public',
    directJobs: 60000,
    social: 2,
    phase: 'progressive',
    incidence: 'Ménages propriétaires et bailleurs sociaux ; filière du bâtiment.',
    basis: 'MaPrimeRénov’ actuelle ≈ 4 Md€ ; objectif de doublement (rapports I4CE).',
  },
  {
    id: 'ferroviaire',
    title: 'Plan ferroviaire : régénérer et rouvrir des lignes',
    desc: 'Investissement dans le réseau, les trains du quotidien et le fret.',
    category: 'transports',
    kind: 'depense_plus',
    amount: 5,
    lever: 'invest_public',
    directJobs: 20000,
    social: 2,
    phase: 'slow',
    incidence: 'Usagers du rail, régions ; besoin documenté sur le réseau structurant.',
    basis: 'Plan « 100 Md€ pour le ferroviaire » d’ici 2040 : ≈ 5 Md€/an supplémentaires.',
  },
  {
    id: 'rer_metropolitains',
    title: 'Financer les RER métropolitains',
    desc: 'Réseaux express régionaux dans une dizaine de grandes agglomérations.',
    category: 'transports',
    kind: 'depense_plus',
    amount: 3,
    lever: 'invest_public',
    directJobs: 12000,
    social: 2,
    phase: 'slow',
    incidence: 'Habitants des couronnes périurbaines ; cofinancement avec les collectivités.',
    basis: 'Estimations SGPI / SNCF Réseau : 15 à 20 Md€ sur la décennie.',
  },
  {
    id: 'velo',
    title: 'Plan vélo et mobilités douces',
    desc: 'Pistes cyclables, stationnement sécurisé, aides à l’achat.',
    category: 'transports',
    kind: 'depense_plus',
    amount: 1,
    lever: 'invest_public',
    directJobs: 5000,
    social: 2,
    phase: 'progressive',
    incidence: 'Collectivités et usagers ; plan actuel ≈ 0,25 Md€/an.',
    basis: 'Quadruplement du plan vélo national.',
  },
  {
    id: 'nucleaire',
    title: 'Financer le programme nucléaire',
    desc: 'Participation publique à la construction de nouveaux réacteurs.',
    category: 'ecologie',
    kind: 'depense_plus',
    amount: 4,
    lever: 'invest_public',
    directJobs: 15000,
    social: 0,
    phase: 'slow',
    incidence: 'Filière nucléaire ; dépenses très étalées dans le temps.',
    basis: 'Programme EPR2 : ≈ 60 Md€ sur 15 ans, part publique lissée.',
  },
  {
    id: 'renouvelables',
    title: 'Accélérer les énergies renouvelables',
    desc: 'Soutien au solaire, à l’éolien et aux réseaux de chaleur.',
    category: 'ecologie',
    kind: 'depense_plus',
    amount: 3,
    lever: 'invest_public',
    directJobs: 12000,
    social: 1,
    phase: 'progressive',
    incidence: 'Producteurs et territoires ; le coût public dépend fortement des prix de marché.',
    basis: 'Charges de service public de l’énergie, hors périodes de prix élevés.',
  },
  {
    id: 'biodiversite',
    title: 'Protéger la biodiversité et l’eau',
    desc: 'Agences de l’eau, aires protégées, renaturation, lutte contre l’artificialisation.',
    category: 'ecologie',
    kind: 'depense_plus',
    amount: 2,
    lever: 'invest_public',
    directJobs: 8000,
    social: 2,
    phase: 'progressive',
    incidence: 'Territoires, agriculture, collectivités.',
    basis: 'Stratégie nationale biodiversité 2030 : besoin ≈ 1 à 3 Md€/an.',
  },
  {
    id: 'adaptation',
    title: 'Adapter le pays au changement climatique',
    desc: 'Digues, réseaux d’eau, îlots de fraîcheur, prévention des incendies.',
    category: 'ecologie',
    kind: 'depense_plus',
    amount: 3,
    lever: 'invest_public',
    directJobs: 12000,
    social: 2,
    phase: 'slow',
    incidence: 'Collectivités exposées ; coût croissant des sinistres climatiques.',
    basis: 'Plan national d’adaptation (PNACC 3) : besoins estimés 2 à 4 Md€/an.',
  },

  /* — Sécurité, justice, défense — */
  {
    id: 'justice',
    title: 'Doubler le budget de la justice en 5 ans',
    desc: 'Magistrats, greffiers, places de prison, numérique judiciaire.',
    category: 'securite',
    kind: 'depense_plus',
    amount: 4,
    lever: 'fonctionnement',
    directJobs: 12000,
    social: 2,
    phase: 'slow',
    incidence: 'Justiciables ; budget par habitant parmi les plus bas d’Europe de l’Ouest.',
    basis: 'Trajectoire de doublement lissée : ≈ +4 Md€/an en 2029.',
  },
  {
    id: 'police',
    title: 'Recruter 10 000 policiers et gendarmes',
    desc: 'Effectifs supplémentaires sur la voie publique et l’investigation.',
    category: 'securite',
    kind: 'depense_plus',
    amount: 0.7,
    lever: 'fonctionnement',
    directJobs: 10000,
    social: 1,
    phase: 'progressive',
    incidence: 'Sécurité du quotidien ; ≈ 70 k€ de coût complet par poste équipé.',
    basis: 'Chiffrage des plans de recrutement 2017-2027.',
  },
  {
    id: 'prisons',
    title: 'Construire 15 000 places de prison',
    desc: 'Programme immobilier pénitentiaire et personnels associés.',
    category: 'securite',
    kind: 'depense_plus',
    amount: 1.5,
    lever: 'invest_public',
    directJobs: 6000,
    social: 0,
    phase: 'slow',
    incidence: 'Administration pénitentiaire ; surpopulation carcérale documentée.',
    basis: 'Programme « 15 000 places » : ≈ 4,5 Md€ d’investissement, lissés.',
  },
  {
    id: 'defense',
    title: 'Porter la défense vers 2,5 % du PIB',
    desc: 'Accélération de la loi de programmation militaire.',
    category: 'securite',
    kind: 'depense_plus',
    amount: 15,
    lever: 'invest_public',
    directJobs: 20000,
    social: 0,
    phase: 'slow',
    incidence: 'Industrie de défense, armées ; défense 2024 ≈ 1,9 % du PIB.',
    basis: '+0,5 point de PIB ≈ 15 Md€/an à terme.',
  },
  {
    id: 'cyber',
    title: 'Renforcer la cyberdéfense',
    desc: 'Protection des administrations, hôpitaux et collectivités.',
    category: 'numerique',
    kind: 'depense_plus',
    amount: 1,
    lever: 'invest_public',
    directJobs: 4000,
    social: 2,
    phase: 'progressive',
    incidence: 'Services publics exposés aux attaques ; filière cybersécurité.',
    basis: 'Ordre de grandeur des plans nationaux de cybersécurité.',
  },
  {
    id: 'secours',
    title: 'Renforcer les moyens de secours',
    desc: 'Pompiers, sécurité civile, moyens aériens contre les incendies.',
    category: 'securite',
    kind: 'depense_plus',
    amount: 1,
    lever: 'invest_public',
    directJobs: 6000,
    social: 3,
    phase: 'progressive',
    incidence: 'SDIS et collectivités ; risques climatiques croissants.',
    basis: 'Pacte capacitaire sécurité civile, ordre de grandeur.',
  },

  /* — Solidarités, famille, logement — */
  {
    id: 'minima',
    title: 'Revaloriser les minima sociaux de 10 %',
    desc: 'RSA, ASS, minimum vieillesse et AAH augmentent.',
    category: 'social',
    kind: 'depense_plus',
    amount: 3,
    lever: 'social_cible',
    social: 2,
    phase: 'immediate',
    incidence: '≈ 4 millions de foyers modestes ; consommation quasi intégrale du gain.',
    basis: 'Masse des minima ≈ 30 Md€/an.',
  },
  {
    id: 'creches',
    title: 'Service public de la petite enfance',
    desc: '200 000 places d’accueil créées en 5 ans.',
    category: 'famille',
    kind: 'depense_plus',
    amount: 4,
    lever: 'fonctionnement',
    directJobs: 40000,
    social: 2,
    phase: 'slow',
    incidence: 'Jeunes parents ; effet favorable sur l’emploi des mères (non modélisé).',
    basis: '≈ 20 k€ de coût complet annuel par place.',
  },
  {
    id: 'logement_social',
    title: 'Construire 150 000 logements sociaux par an',
    desc: 'Aides à la pierre et soutien aux bailleurs sociaux.',
    category: 'logement',
    kind: 'depense_plus',
    amount: 4,
    lever: 'invest_public',
    directJobs: 45000,
    social: 3,
    phase: 'progressive',
    incidence: '≈ 2,7 millions de demandes en attente ; filière du bâtiment.',
    basis: 'Aides à la pierre et compensation de la RLS : ordre de grandeur 3 à 5 Md€.',
  },
  {
    id: 'hebergement',
    title: 'Créer des places d’hébergement d’urgence',
    desc: 'Sortie de rue, logement accompagné, places pérennes.',
    category: 'social',
    kind: 'depense_plus',
    amount: 1.5,
    lever: 'social_cible',
    directJobs: 8000,
    social: 3,
    phase: 'immediate',
    incidence: 'Personnes sans domicile ; ≈ 200 000 places actuellement financées.',
    basis: 'Budget hébergement d’urgence ≈ 3 Md€ ; hausse de 50 %.',
  },
  {
    id: 'apl_hausse',
    title: 'Revaloriser les aides au logement',
    desc: 'Les APL augmentent de 10 % et les barèmes sont réindexés.',
    category: 'logement',
    kind: 'depense_plus',
    amount: 1.6,
    lever: 'social_cible',
    social: 2,
    phase: 'immediate',
    incidence: '≈ 6 millions de ménages allocataires ; effet partiel sur les loyers.',
    basis: 'Masse des APL ≈ 16 Md€.',
  },
  {
    id: 'handicap',
    title: 'Renforcer l’accompagnement du handicap',
    desc: 'Places en établissement, AESH à l’école, accessibilité.',
    category: 'social',
    kind: 'depense_plus',
    amount: 3,
    lever: 'fonctionnement',
    directJobs: 30000,
    social: 3,
    phase: 'progressive',
    incidence: 'Personnes handicapées et familles ; besoins d’accompagnement scolaire documentés.',
    basis: 'Dépense handicap ≈ 60 Md€ ; effort supplémentaire de 5 %.',
  },
  {
    id: 'aide_alimentaire',
    title: 'Renforcer l’aide alimentaire',
    desc: 'Soutien aux associations et chèque alimentaire ciblé.',
    category: 'social',
    kind: 'depense_plus',
    amount: 1,
    lever: 'social_cible',
    social: 3,
    phase: 'immediate',
    incidence: '≈ 5 millions de personnes recourant à l’aide alimentaire.',
    basis: 'Fonds actuels ≈ 0,15 Md€ ; projets de chèque alimentaire chiffrés autour de 1 Md€.',
  },
  {
    id: 'rsa_jeunes',
    title: 'Ouvrir le RSA aux 18-25 ans',
    desc: 'Le revenu de solidarité active est étendu aux jeunes majeurs sans ressources.',
    category: 'social',
    kind: 'depense_plus',
    amount: 3,
    lever: 'social_cible',
    social: 1,
    phase: 'progressive',
    incidence: 'Jeunes sans emploi ni formation ; débat sur l’articulation avec l’accompagnement.',
    basis: 'Chiffrages parlementaires : 2 à 4 Md€ selon les conditions d’accès.',
  },
  {
    id: 'allocations_familiales',
    title: 'Revaloriser les allocations familiales',
    desc: 'Hausse générale et ouverture dès le premier enfant.',
    category: 'famille',
    kind: 'depense_plus',
    amount: 3,
    lever: 'social_cible',
    social: 2,
    phase: 'immediate',
    incidence: 'Familles avec enfants ; natalité en baisse depuis 2010.',
    basis: 'Masse des allocations familiales ≈ 13 Md€.',
  },
  {
    id: 'conge_parental',
    title: 'Créer un congé parental mieux rémunéré',
    desc: 'Congé plus court mais indemnisé à hauteur d’une grande part du salaire.',
    category: 'famille',
    kind: 'depense_plus',
    amount: 2,
    lever: 'social_cible',
    social: 2,
    phase: 'progressive',
    incidence: 'Jeunes parents ; modèle inspiré des pays nordiques.',
    basis: 'Projets de « congé familial » chiffrés autour de 2 Md€.',
  },

  /* — Retraites — */
  {
    id: 'pensions_revalo',
    title: 'Revaloriser les pensions au-dessus de l’inflation',
    desc: 'Les retraites augmentent 1 point de plus que les prix.',
    category: 'retraites',
    kind: 'depense_plus',
    amount: 4,
    lever: 'social_cible',
    social: 2,
    phase: 'immediate',
    incidence: '17 millions de retraités ; coût pérenne (effet base).',
    basis: 'Masse des pensions ≈ 400 Md€ : 1 point ≈ 4 Md€.',
  },
  {
    id: 'minimum_retraite',
    title: 'Porter le minimum de pension à 85 % du SMIC',
    desc: 'Le minimum contributif est relevé pour les carrières complètes.',
    category: 'retraites',
    kind: 'depense_plus',
    amount: 2,
    lever: 'social_cible',
    social: 3,
    phase: 'progressive',
    incidence: 'Retraités à faibles pensions, surtout des femmes à carrière incomplète.',
    basis: 'Chiffrages de la réforme 2023 sur le minimum contributif.',
  },
  {
    id: 'penibilite',
    title: 'Élargir les départs anticipés pour pénibilité',
    desc: 'Critères de pénibilité rétablis et élargis.',
    category: 'retraites',
    kind: 'depense_plus',
    amount: 3,
    lever: 'social_cible',
    social: 3,
    phase: 'progressive',
    incidence: 'Salariés exposés (port de charges, postures, travail de nuit).',
    basis: 'Estimations sur le rétablissement des 4 critères supprimés en 2017.',
  },
  {
    id: 'retraite_age_baisse',
    title: 'Revenir à la retraite à 62 ans',
    desc: 'L’âge légal est ramené à son niveau d’avant la réforme de 2023.',
    category: 'retraites',
    kind: 'depense_plus',
    amount: 12,
    lever: 'social_cible',
    social: 3,
    phase: 'slow',
    incidence: 'Salariés proches de la retraite ; effet inverse du report d’âge.',
    basis: 'Symétrique du chiffrage du report d’âge (COR) : ≈ 10-15 Md€ à horizon 5 ans.',
  },

  /* — Fonction publique, État — */
  {
    id: 'point_indice',
    title: 'Revaloriser le point d’indice',
    desc: 'Le salaire de base des 5,7 millions d’agents publics augmente.',
    category: 'fonction_publique',
    kind: 'depense_plus',
    amount: 10,
    param: { unit: '%', min: 1, max: 5, step: 1, default: 3, perUnit: 3.3 },
    lever: 'fonctionnement',
    social: 2,
    phase: 'immediate',
    incidence: 'Tous les agents publics ; coût partagé État, hôpitaux, collectivités.',
    basis: '≈ 3,3 Md€ par point de % (masse salariale publique ≈ 330 Md€).',
  },
  {
    id: 'primes_terrain',
    title: 'Primes pour les agents de terrain',
    desc: 'Revalorisation ciblée sur les métiers en tension du service public.',
    category: 'fonction_publique',
    kind: 'depense_plus',
    amount: 2,
    lever: 'fonctionnement',
    social: 2,
    phase: 'immediate',
    incidence: 'Soignants, enseignants, forces de sécurité, travailleurs sociaux.',
    basis: 'Ordre de grandeur des plans de revalorisation ciblés récents.',
  },
  {
    id: 'services_publics_ruraux',
    title: 'Rouvrir des services publics de proximité',
    desc: 'Maisons France Services, trésoreries, guichets physiques.',
    category: 'territoires',
    kind: 'depense_plus',
    amount: 1,
    lever: 'fonctionnement',
    directJobs: 10000,
    social: 3,
    phase: 'progressive',
    incidence: 'Territoires ruraux et périurbains ; publics éloignés du numérique.',
    basis: 'Réseau France Services actuel ≈ 0,15 Md€ ; densification forte.',
  },
  {
    id: 'numerique_etat',
    title: 'Moderniser le numérique de l’État',
    desc: 'Refonte des systèmes d’information vieillissants et souveraineté.',
    category: 'numerique',
    kind: 'depense_plus',
    amount: 1.5,
    lever: 'invest_public',
    directJobs: 5000,
    social: 1,
    phase: 'progressive',
    incidence: 'Administrations et usagers ; dette technique documentée par la Cour des comptes.',
    basis: 'Programmes de transformation numérique de l’État, ordre de grandeur.',
  },

  /* — Économie, territoires, culture, international — */
  {
    id: 'reindustrialisation',
    title: 'Plan de réindustrialisation',
    desc: 'Aides à l’implantation, foncier industriel, filières stratégiques.',
    category: 'economie',
    kind: 'depense_plus',
    amount: 6,
    lever: 'invest_public',
    directJobs: 10000,
    social: 1,
    phase: 'progressive',
    incidence: 'Industrie manufacturière ; part de l’industrie ≈ 10 % du PIB.',
    basis: 'Ordre de grandeur des volets industriels de France 2030.',
  },
  {
    id: 'agriculture_transition',
    title: 'Accompagner la transition agricole',
    desc: 'Aide au revenu, conversion, installation de nouveaux agriculteurs.',
    category: 'agriculture',
    kind: 'depense_plus',
    amount: 3,
    lever: 'social_cible',
    social: 2,
    phase: 'progressive',
    incidence: 'Exploitations agricoles ; renouvellement des générations (50 % de départs d’ici 10 ans).',
    basis: 'Compléments nationaux à la PAC : ordre de grandeur 2 à 4 Md€.',
  },
  {
    id: 'outre_mer',
    title: 'Plan de rattrapage outre-mer',
    desc: 'Eau, écoles, hôpitaux, logement dans les territoires ultramarins.',
    category: 'territoires',
    kind: 'depense_plus',
    amount: 2,
    lever: 'invest_public',
    directJobs: 8000,
    social: 3,
    phase: 'progressive',
    incidence: '2,8 millions d’habitants ; écarts de services publics documentés.',
    basis: 'Ordre de grandeur des plans de convergence ultramarins.',
  },
  {
    id: 'culture',
    title: 'Renforcer la culture et le patrimoine',
    desc: 'Création, patrimoine, éducation artistique, lecture publique.',
    category: 'culture',
    kind: 'depense_plus',
    amount: 1.5,
    lever: 'fonctionnement',
    directJobs: 6000,
    social: 1,
    phase: 'immediate',
    incidence: 'Secteur culturel ; budget du ministère ≈ 4 Md€.',
    basis: 'Hausse de l’ordre de 35 % du budget de la mission Culture.',
  },
  {
    id: 'audiovisuel_plus',
    title: 'Sécuriser le financement de l’audiovisuel public',
    desc: 'Ressource pérenne et niveau de financement relevé.',
    category: 'culture',
    kind: 'depense_plus',
    amount: 0.6,
    lever: 'fonctionnement',
    social: 0,
    phase: 'immediate',
    incidence: 'France Télévisions, Radio France, Arte ; ≈ 4 Md€ de dotation actuelle.',
    basis: 'Comparaison européenne du financement par habitant.',
  },
  {
    id: 'aide_developpement',
    title: 'Porter l’aide au développement à 0,7 % du RNB',
    desc: 'Objectif international réaffirmé de solidarité internationale.',
    category: 'international',
    kind: 'depense_plus',
    amount: 6,
    lever: 'social_cible',
    social: -1,
    phase: 'slow',
    incidence: 'Pays partenaires ; APD française ≈ 0,5 % du RNB.',
    basis: 'Écart à l’objectif de 0,7 % : ≈ 5 à 7 Md€.',
  },
  {
    id: 'sport',
    title: 'Investir dans le sport et les équipements',
    desc: 'Piscines, gymnases, clubs, sport-santé après les Jeux.',
    category: 'culture',
    kind: 'depense_plus',
    amount: 1,
    lever: 'invest_public',
    directJobs: 6000,
    social: 2,
    phase: 'progressive',
    incidence: 'Collectivités et clubs ; vétusté d’une part importante des équipements.',
    basis: 'Plans « 5 000 équipements sportifs » et rénovation des piscines.',
  },

  /* ═════════════ DÉPENSES EN BAISSE ═════════════ */

  {
    id: 'retraite_age',
    title: 'Reporter l’âge légal de départ en retraite',
    desc: 'L’âge légal recule au-delà de 64 ans.',
    category: 'retraites',
    kind: 'depense_moins',
    amount: 10,
    param: { unit: 'an', min: 1, max: 2, step: 1, default: 1, perUnit: 10 },
    lever: 'social_cible',
    social: -3,
    phase: 'slow',
    incidence: 'Salariés proches de la retraite, surtout carrières longues et métiers pénibles.',
    basis: '≈ 10 Md€/an d’économies par année d’âge à horizon 5 ans (COR, études 2023).',
  },
  {
    id: 'retraites_gel',
    title: 'Sous-indexer les pensions un an',
    desc: 'Les pensions augmentent 1 point de moins que l’inflation, une année.',
    category: 'retraites',
    kind: 'depense_moins',
    amount: 4,
    lever: 'social_cible',
    social: -3,
    phase: 'immediate',
    incidence: '17 millions de retraités ; économie pérenne (effet base).',
    basis: 'Masse des pensions ≈ 400 Md€ : 1 point d’indexation ≈ 4 Md€.',
  },
  {
    id: 'regimes_speciaux',
    title: 'Fermer les régimes spéciaux restants',
    desc: 'Alignement progressif des derniers régimes sur le régime général.',
    category: 'retraites',
    kind: 'depense_moins',
    amount: 2,
    lever: 'social_cible',
    social: -1,
    phase: 'slow',
    incidence: 'Agents concernés ; extinction très progressive (« clause du grand-père »).',
    basis: 'Subventions d’équilibre aux régimes spéciaux ≈ 8 Md€, économie partielle à 5 ans.',
  },
  {
    id: 'decote_surcote',
    title: 'Durcir la décote avant l’âge du taux plein',
    desc: 'Le malus appliqué aux départs anticipés augmente.',
    category: 'retraites',
    kind: 'depense_moins',
    amount: 2,
    lever: 'social_cible',
    social: -3,
    phase: 'progressive',
    incidence: 'Assurés partant sans carrière complète, souvent aux revenus modestes.',
    basis: 'Ordre de grandeur des variantes étudiées par le COR.',
  },
  {
    id: 'fonctionnaires_nr',
    title: 'Ne pas remplacer 1 départ sur 3 (hors santé-éducation)',
    desc: 'Les effectifs administratifs diminuent au fil des départs en retraite.',
    category: 'fonction_publique',
    kind: 'depense_moins',
    amount: 4,
    lever: 'fonctionnement',
    directJobs: -60000,
    social: -2,
    phase: 'slow',
    incidence: 'Services administratifs de l’État et opérateurs.',
    basis: '≈ 60 000 postes en 5 ans × 65 k€ ; montée en charge lente.',
  },
  {
    id: 'temps_travail_fp',
    title: 'Porter le temps de travail à 37 heures dans la fonction publique',
    desc: 'Hausse du temps de travail sans hausse d’effectifs.',
    category: 'fonction_publique',
    kind: 'depense_moins',
    amount: 3,
    lever: 'fonctionnement',
    social: -3,
    phase: 'progressive',
    incidence: 'Agents publics ; suppose une réorganisation des services.',
    basis: 'Chiffrages parlementaires : 3 à 5 Md€ selon le périmètre.',
  },
  {
    id: 'jours_carence',
    title: 'Allonger le délai de carence des arrêts maladie',
    desc: 'Le délai non indemnisé passe à trois jours, public et privé.',
    category: 'sante',
    kind: 'depense_moins',
    amount: 1.5,
    lever: 'social_cible',
    social: -3,
    phase: 'immediate',
    incidence: 'Salariés en arrêt court ; report partiel sur les employeurs et les complémentaires.',
    basis: 'Chiffrages PLFSS successifs : 0,9 à 2 Md€.',
  },
  {
    id: 'franchises',
    title: 'Doubler les franchises médicales',
    desc: 'Reste à charge accru sur les boîtes de médicaments et les consultations.',
    category: 'sante',
    kind: 'depense_moins',
    amount: 1,
    lever: 'social_cible',
    social: -2,
    phase: 'immediate',
    incidence: 'Patients, davantage les malades chroniques ; report partiel sur les mutuelles.',
    basis: 'Rendement du doublement de 2024 : ≈ 0,8 Md€.',
  },
  {
    id: 'arrets_travail',
    title: 'Encadrer plus strictement les arrêts de travail',
    desc: 'Contrôles renforcés et durée maximale de prescription.',
    category: 'sante',
    kind: 'depense_moins',
    amount: 2,
    lever: 'social_cible',
    social: -2,
    phase: 'progressive',
    incidence: 'Assurés en arrêt ; dépense d’indemnités journalières ≈ 17 Md€.',
    basis: 'Objectifs d’économies des PLFSS récents.',
  },
  {
    id: 'medicaments',
    title: 'Négocier plus dur le prix des médicaments',
    desc: 'Référencement européen et génériques imposés.',
    category: 'sante',
    kind: 'depense_moins',
    amount: 2,
    lever: 'fonctionnement',
    social: 0,
    phase: 'progressive',
    incidence: 'Industrie pharmaceutique ; dépense de médicaments ≈ 34 Md€.',
    basis: 'Économies CEPS renforcées : 1,5 à 2,5 Md€.',
  },
  {
    id: 'ame',
    title: 'Restreindre l’aide médicale d’État',
    desc: 'Le panier de soins des personnes étrangères en situation irrégulière est réduit.',
    category: 'sante',
    kind: 'depense_moins',
    amount: 0.6,
    lever: 'social_cible',
    social: -2,
    phase: 'immediate',
    incidence: '≈ 400 000 bénéficiaires ; effets sanitaires et de report vers l’hôpital discutés.',
    basis: 'Budget de l’AME ≈ 1,2 Md€ ; économie partielle.',
  },
  {
    id: 'chomage_regles',
    title: 'Durcir l’assurance chômage',
    desc: 'Durée d’indemnisation réduite quand la conjoncture est bonne.',
    category: 'social',
    kind: 'depense_moins',
    amount: 4,
    lever: 'social_cible',
    social: -2,
    phase: 'progressive',
    incidence: 'Demandeurs d’emploi indemnisés ; effets d’activation débattus, non modélisés.',
    basis: 'Chiffrages Unédic des réformes 2023-2025.',
  },
  {
    id: 'apl_baisse',
    title: 'Réduire les aides au logement',
    desc: 'Barèmes resserrés et sous-indexation des APL.',
    category: 'logement',
    kind: 'depense_moins',
    amount: 1.5,
    lever: 'social_cible',
    social: -3,
    phase: 'immediate',
    incidence: '≈ 6 millions de ménages allocataires, majoritairement modestes.',
    basis: 'Masse des APL ≈ 16 Md€ ; économie de l’ordre de 10 %.',
  },
  {
    id: 'prestations_gel',
    title: 'Sous-indexer les prestations sociales',
    desc: 'Prestations familiales et minima augmentent moins vite que les prix, une année.',
    category: 'social',
    kind: 'depense_moins',
    amount: 2.5,
    lever: 'social_cible',
    social: -3,
    phase: 'immediate',
    incidence: 'Allocataires de prestations non contributives.',
    basis: 'Masse des prestations concernées ≈ 250 Md€ : 1 point ≈ 2,5 Md€.',
  },
  {
    id: 'aides_entreprises',
    title: 'Raboter les aides aux entreprises de 10 %',
    desc: 'Niches, subventions et exonérations les moins évaluées sont réduites.',
    category: 'fiscalite_entreprises',
    kind: 'depense_moins',
    amount: 6,
    lever: 'tax_entreprises',
    social: 0,
    phase: 'progressive',
    incidence: 'Entreprises bénéficiaires (masse totale estimée 60-110 Md€ selon périmètre).',
    basis: 'Rapports France Stratégie / travaux universitaires sur les aides aux entreprises.',
  },
  {
    id: 'apprentissage_rabot',
    title: 'Recentrer les aides à l’apprentissage',
    desc: 'La prime aux employeurs est réservée aux niveaux infra-bac +2.',
    category: 'emploi',
    kind: 'depense_moins',
    amount: 2,
    lever: 'social_cible',
    social: -1,
    phase: 'immediate',
    incidence: 'Employeurs d’apprentis du supérieur ; effet d’aubaine documenté.',
    basis: 'Coût total du soutien à l’apprentissage ≈ 10 Md€.',
  },
  {
    id: 'contrats_aides',
    title: 'Réduire les contrats aidés',
    desc: 'Le nombre de contrats subventionnés dans le secteur non marchand diminue.',
    category: 'emploi',
    kind: 'depense_moins',
    amount: 1.5,
    lever: 'fonctionnement',
    directJobs: -40000,
    social: -2,
    phase: 'progressive',
    incidence: 'Associations et collectivités employeuses ; publics éloignés de l’emploi.',
    basis: 'Coût unitaire ≈ 8 à 10 k€/an ; ordre de grandeur des vagues de réduction passées.',
  },
  {
    id: 'agences',
    title: 'Fusionner agences et comités',
    desc: 'Rationalisation des opérateurs de l’État aux missions redondantes.',
    category: 'fonctionnement_etat',
    kind: 'depense_moins',
    amount: 2,
    lever: 'fonctionnement',
    social: 0,
    phase: 'progressive',
    incidence: 'Opérateurs publics (≈ 80 Md€ de budgets cumulés).',
    basis: 'Rapports IGF sur les agences : 1,5 à 3 Md€ mobilisables.',
  },
  {
    id: 'train_vie',
    title: 'Réduire le train de vie de l’État',
    desc: 'Immobilier, parc automobile, communication, frais de représentation.',
    category: 'fonctionnement_etat',
    kind: 'depense_moins',
    amount: 1,
    lever: 'fonctionnement',
    social: 2,
    phase: 'immediate',
    incidence: 'Administrations centrales.',
    basis: 'Revues de dépenses successives : ≈ 1 Md€ réaliste.',
  },
  {
    id: 'conseil_prives',
    title: 'Diviser par deux le recours aux cabinets de conseil',
    desc: 'Les prestations intellectuelles externes sont réinternalisées.',
    category: 'fonctionnement_etat',
    kind: 'depense_moins',
    amount: 0.5,
    lever: 'fonctionnement',
    social: 3,
    phase: 'immediate',
    incidence: 'Cabinets prestataires ; suppose de recruter en interne.',
    basis: 'Dépense de conseil de l’État ≈ 1 Md€ (rapport sénatorial 2022).',
  },
  {
    id: 'mille_feuille',
    title: 'Simplifier le millefeuille territorial',
    desc: 'Compétences clarifiées, doublons administratifs supprimés entre échelons.',
    category: 'territoires',
    kind: 'depense_moins',
    amount: 3,
    lever: 'fonctionnement',
    directJobs: -30000,
    social: -1,
    phase: 'slow',
    incidence: 'Collectivités et leurs agents ; économies très débattues.',
    basis: 'Estimations variables (1 à 10 Md€) ; hypothèse prudente retenue.',
  },
  {
    id: 'dotations_baisse',
    title: 'Réduire les dotations aux collectivités',
    desc: 'La dotation globale de fonctionnement diminue.',
    category: 'territoires',
    kind: 'depense_moins',
    amount: 5,
    lever: 'fonctionnement',
    social: -2,
    phase: 'progressive',
    incidence: 'Communes, départements, régions — report possible sur les impôts locaux ou les services.',
    basis: 'DGF ≈ 27 Md€ ; baisse comparable à celle de 2014-2017.',
  },
  {
    id: 'subventions_assos',
    title: 'Réduire les subventions aux associations',
    desc: 'Les crédits d’intervention associatifs sont resserrés.',
    category: 'social',
    kind: 'depense_moins',
    amount: 1,
    lever: 'fonctionnement',
    directJobs: -15000,
    social: -2,
    phase: 'immediate',
    incidence: 'Secteur associatif (sport, culture, social, environnement).',
    basis: 'Subventions publiques aux associations ≈ 10 Md€ hors collectivités.',
  },
  {
    id: 'niches_vertes',
    title: 'Supprimer les niches fiscales brunes',
    desc: 'Avantages fiscaux sur le gazole non routier et exonérations kérosène domestiques.',
    category: 'ecologie',
    kind: 'depense_moins',
    amount: 3,
    lever: 'tax_conso',
    social: -2,
    phase: 'progressive',
    incidence: 'BTP, agriculture, transport aérien intérieur.',
    basis: 'Inventaire I4CE des dépenses fiscales défavorables au climat (≈ 3 Md€ ciblables).',
  },
  {
    id: 'audiovisuel_baisse',
    title: 'Réduire le financement de l’audiovisuel public',
    desc: 'La dotation aux sociétés publiques est diminuée d’un quart.',
    category: 'culture',
    kind: 'depense_moins',
    amount: 1,
    lever: 'fonctionnement',
    directJobs: -3000,
    social: -1,
    phase: 'progressive',
    incidence: 'France Télévisions, Radio France, Arte et leurs salariés.',
    basis: 'Dotation actuelle ≈ 4 Md€.',
  },
  {
    id: 'defense_baisse',
    title: 'Ralentir la programmation militaire',
    desc: 'Le rythme de hausse du budget des armées est réduit.',
    category: 'securite',
    kind: 'depense_moins',
    amount: 5,
    lever: 'invest_public',
    directJobs: -8000,
    social: -1,
    phase: 'progressive',
    incidence: 'Industrie de défense et armées ; engagements pluriannuels en cours.',
    basis: 'Écart à la trajectoire de la LPM 2024-2030.',
  },
  {
    id: 'gel_depenses',
    title: 'Geler les dépenses de fonctionnement de l’État',
    desc: 'Norme de dépense en euros courants : pas de hausse, hors salaires et dette.',
    category: 'fonctionnement_etat',
    kind: 'depense_moins',
    amount: 7,
    lever: 'fonctionnement',
    social: -1,
    phase: 'progressive',
    incidence: 'Toutes les administrations d’État : l’inflation érode les budgets réels.',
    basis: 'Effet cumulé d’un gel nominal sur ≈ 130 Md€ de crédits, à 2 % d’inflation.',
  },
  {
    id: 'europe_contribution',
    title: 'Réduire la contribution française au budget de l’UE',
    desc: 'La France négocie une baisse de sa contribution nette.',
    category: 'international',
    kind: 'depense_moins',
    amount: 2,
    lever: 'fonctionnement',
    social: 0,
    phase: 'slow',
    incidence: 'Budget européen ; suppose un accord unanime des États membres.',
    basis: 'Contribution française ≈ 24 Md€ ; baisse marginale négociée.',
  },
];
